{% set name = "spherical-geometry" %}
{% set version = "1.2.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spherical_geometry-{{ version }}.tar.gz
  sha256: a496276d34ab906039332f77498921f8385807d2574fa63353efb3dba145a9f6

build:
  script:
    - {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win and py3k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools-scm
    - pip
    - wheel
    - numpy
  run:
    - python
    - astropy >=5.0.4
    - numpy >=1.18
    - charset-normalizer

test:
  imports:
    - spherical_geometry
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.stsci.edu/resources/software_hardware/stsci_python
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: A Python package for handling spherical polygons that represent arbitrary regions of the sky
  description: |
    The `spherical_geometry` library is a Python package for handling
    spherical polygons that represent arbitrary regions of the sky. It has
    classes for representing and operating on spherical polygons, arbitrary
    areas on the sky sphere enclosed by great circle arcs, and great circle
    arcs.
  doc_url: http://spacetelescope.github.io/spherical_geometry/spherical_geometry/
  dev_url: https://github.com/spacetelescope/spherical_geometry

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - bernie-simon
    - pllim
    - jhunkeler
