travis:
  secure:
    BINSTAR_TOKEN: OSctm1PofMtH264R+NOsICCNdmFVKfD7q39NqWAOGjAraGN2qQjr9ZFuNGBcrZd0XoO+2DKZ4nMz/M1esnRuY9Ja3Q5hIdAeTLP/Mk+2AIcsEzcP1Oot+fOI1xS9nvj+5qDtFa5tRdcG1sgqeiEsJ4XVTEpm5FprRoZSLBkiMqtttUS4RqKrCb4DU+PqYXNQDrociMKtrZbtiXaIYkSJp7JGMCEcbQpz8713m/j3r6sNr8zvWZCHfEgPLJEoAGy0mowXWbRlCcWsfaDZzzHzKFBTj3XXBa+NZz3AEGCXEQ6pCB58X8LJ8Ch7UQ1u7Zuq8oxDLipfIZjUXxmyokvfFH0Qut5hz+v848usixpWp8ucfrEhfVwlnVCS7s1R1J7naDku7K+PM2TsXY9on/5DdYJNGhKng2Az7w6j+EG/dmYss2PxMLCx5bG0E5K4/WbmOzlR7ZsXXQ4vX7gBoiCCJS4Z4uBCJA4dBAS0oYsqcoPGCYLxUlDs3xaqV3otIRGQd6kmSPg2rLpPeJ+s1D6lckEHmugftjgIEEvtVqZj+RCCvsWM3+2xe30c1LKdl4OsWjAsttrus09xrcAiFD60xTulmj7sSDnpmX3RbvINPveSaRP4t7mXWTSf0My6qKWRsAc3gFoAVunZb/QbAypfcEebcglmBc36h29Kc16wEp0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
