travis:
  secure:
    BINSTAR_TOKEN: q6e9FMvt9+6BUURFVTLtS532IqXpso2tIO5ytEI4Ya4awCpI7APITtyzyEBfgXynoS7WVFiDjdbfVAg+AGcWxdWsFoP0NqkyGPX8w47vjapCtZHOucORv2K/n2hME6uHlOwtnvGwtdC5+/JoYkA4pBY1Bx8SUxFgoi5Z2WnIM/fCYbMh/deuEUiWszEeN68LJji4dahEpjJwiZhySA7FQ/v2qblYlMEqh50jXez262pVvuLFqS1nDkgPR1NEpM4KLkcEZ2a4IyicbEGT4gPYzcWSbWjIxTk14HiUX2imS3ZTMu27pObMljQ18/daTMgtAH4Cx02qllvxE4aCs6TXSzknLeMX7v3YEv/d+Sd3PhM003sO6lNghjyD13vze7sktOtPQkXnpr0ov8UEV9XBUq0H6xvirT17JSbhQPw+5ccGi8hbgT0/dU/0Ak51cMQINOT3UQlQnZRoagWzmI3ou1sf73FeCb3sIPthtuA5j7lVH1YpTlib0DcnWmPuB2ZJu8XD8HeJr7qiZgoBxUmlGI606uVD3hFqVbmN0vIl7073tX2LmkjoL342nVEVHrWAuIEVb3E6f5gzaX4/1zETn1JVX/Rapv/4M2J82nC4HJtLovKE6r0X28ZvVDSPZHz81EbToe8zV8xl8LsoVaud9WO0nZPnKfjkxkLt6mLwRRI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
