travis:
  secure:
    BINSTAR_TOKEN: 0+j3oyfnuYTpSn91n+kTAbjNyQ68RZb86cvEQK5v9UhFZxPH8dG+3cwSfxm1u3XiC3aicomvWDLPJMO9yzykkwl3AjWY/PAWJJ6oPX+RFUJREUjFJiQSkq/fcGN0J1SEV8Jqg5+Roq7xnD/K/H671OXshIAveHk1zElEkzTYlMcrsudlcuCTL1DhBBhuahs/LRLbILKxIUVcl8l1Rh114s7A8iibLl7ZnUKYok+kRxwtvCXCuLekuj3C3cjqtfnH3OuPLSRrZhOZ62kaLixzXwqsp5xzN7FNJjH3Wbzfg1ej+KNOU8cCvhBMEIIu1ZJVc2enpBw3ay7mXT8tzzIsNvRhvRcqc0RfgErtAxJRQ9nEgWRuy7oDA/S1sfOvekwIYF4a1HF49bH257YX9CRMLicKZkIMO/DB/8FMeMktc+7cZq0motu7rFXfWTPCmlc0iI7gBMOwZz+ALRYJCmldsO61nPTiOB6citFirrV1/BEwcEWmENE+PB41MUWA4IxXXOy+THvSAowMKYZGtTcTIpUt3ADcPD31bYiGIs46I8Ae3cLjSXGDlB9aHnBFo3wFhFS2riJbyX4o3dA4RPq8zIk1y1hDgsx7R3HPgrU2zb37DNyeCX7z0WukNnICqbJ4RZZ0l5uw+TmK1Kv6gbYZaQg1vUSdkwvKuVbrrjVIOZc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
