appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 4MCiTCd9VjM45JtUbnTAhU/MgCtQRijitgzjeXoz6PM83X29kzbg2ImZy64P6UKAZV59grI5OAKNNMPZkbm5Ku17hx00HyP2Cr1grbj4GTGHEk3Y9shhP66nydEgYlfxayZAqKOAQj2EB0st5SQ7K41XRvMdSOM0AXA86WHtxczobN73K32XKDt3zZ8M7yshyClxMgeyth3J/hbOh/LYtp5gghRUSi+sNkOuPjf1zWgsCJDaq10SoW00KbD0cJhdDUA/Dgxqkwrib2N40w2QENjDLGIDqUdNd5yIegVfLb3kliYGfbE0kdFKXqMfUDOUWzQRrdl1/2CBvc092MIsWRkLY6fgforg3HSCxnwfuQsUnw+8fw1OD2V3c5EWPTHQF6RgwQRoJqpgpaQMWLeY2RBh38zoe9VCfTHkhQ2lCq2q7ZvMN91GiNFx4gEqCzi5C2uwLJImim1xlVqYId/mYBhtccocMUb7qpVRZjvfSRL6Keaq58Dq0uQZ0S47JsZ5nal+GHwHzig+dnITbPi/eaLCpE1VEe8QzpXkEQZjJT7hzy9/NdTN0wZS7fCQ8IPcm9w/m2WuLwivjex9yg62rY/GjdWbBrh0ClhY1FdwYR1Gc05ELWVW0vYCkVnAXlAlLz7rDpGWZq7113Gfgq1KjniQbHWNjbtE+cR0APoQAbU=}
